### PR TITLE
Fix for JoinColumn issue with non primary key

### PR DESCRIPTION
**Pull request by radovanradic**
Making this draft request as potential fix for #1793 since I guess there could be cleaner solutions

### CODE REVIEW

**Comment by dstepanov** [comment]
I think we can simply annotate `@MappedProperty` with a correct value in the entity visitor.

**Comment by radovanradic** [comment]
> I think we can simply annotate `@MappedProperty` with a correct value in the entity visitor.

Ok, I am closing this PR. Also, have no idea how to do it via MappedProperty so hopefully someone else will be able to resolve this issue.

**Comment by radovanradic** [comment]
This is an old PR. Tried to implement using `@MappedProperty` field name in `MappedEntityVisitor` and this works for select but doesn't work when inserting/binding value since by default our implementation uses associated entity `@Id` field. I think this initial solution may better so reopening it now after pulling latest changes in the old branch.

**Review by dstepanov — APPROVED** [review]

**Comment by radovanradic** [comment]
Might need to redo

**Pull request closed without merging**
