### PR TITLE
Fix the set Offset on JPA/Hibernate

### PR DESCRIPTION
**Pull request by kareemelzayat**
The PR is to use the correct method to set the SQL OFFSET

### CODE REVIEW

**Comment by kareemelzayat** [comment]
@dstepanov can we merge this?

**Comment by kareemelzayat** [comment]
@dstepanov I would like to have this as part of Micronaut 4.3.2. How can I achieve that?

**Comment by dstepanov** [comment]
I will merge it

**Comment by dstepanov** [comment]
@kareemelzayat Can you please resign the CLA?

**Comment by kareemelzayat** [comment]
@dstepanov done 👍

**Pull request merged**
