### PR TITLE
Update jdbcQuickStart.adoc to bump Jakarta versión to v3.0.0

### PR DESCRIPTION
**Pull request by alejandropg**
I propose to update the Jakarta version to the `3.0.0` because this version contains the new packages `jakarta.persistence.criteria`.

What do you think? Is correct?

### CODE REVIEW

**Comment by dstepanov** [comment]
That would also require to update all examples to jakarta package instead of javax.

**Comment by alejandropg** [comment]
Hi @dstepanov 

The problem is that actually the examples of the section 8.1.4.1 (https://micronaut-projects.github.io/micronaut-data/latest/guide/index.html#criteriaExecuteQuery) doesn't compile because with the versión 2.2.2 you cannot find the class `CriteriaBuilder` because in the class `io.micronaut.data.repository.jpa.criteria.PredicateSpecification` uses the new Jakarta package.

So, yes your idea of update all the examples to the new jakarta packaging sounds that could be the better option.

**Comment by dstepanov** [comment]
Just to clarify, we remap JPA annotations to our own so you don’t really need them at the runtime classpath but the criteria are based on Jakarta JPA v3 API

**Comment by alejandropg** [comment]
Correct, the problem is not with the annotations just with the criteria API.

The problem is with the class `PredicateSpecification` that you need to import if you want to use the `JpaSpecificationExecutor`

```
package io.micronaut.data.repository.jpa.criteria;

import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;

public interface PredicateSpecification<T> {

...
````

As you can see the there are several classes imported from the new Jakarta package. So you need to use the versión 3.0.0.

I could import both, the 2.2.2 and the 3.0.0, but I think in general this is not a good idea 😅

If you want I could try to make the update in the folder `doc-examples` (I don't know if I have to touch in more places).

**Comment by dstepanov** [comment]
If you can migrate all `javax.` to `jakarta.` packages in the samples that would be great

**Comment by dstepanov** [comment]
Except for the Hibernate code...

**Comment by alejandropg** [comment]
Hi @dstepanov, I already did the changes. I only changed the JDBC's example projects, that are the only ones that use jakarta persistence directly (the other ones uses the Hibernate dependency).

Also fix a couple of Asciidoc references.

Pleas tell me if this is correct or if you want I change something more.

Thanks!

**Comment by dstepanov** [comment]
Looks great! Thanks for the contribution!

**Comment by alejandropg** [comment]
Really a pleasure ☺️

@dstepanov I show that there are more code that maybe could be moved to the new jakarta package. For example `data-tck` or `benchmarks/benchmark-micronaut-data-jdbc` (in general all the code that doesn't depends on Hiberante)

What do you think? If you want I could migrate them in separate pull request.

**Comment by dstepanov** [comment]
Yeah, benchmarks can be migrated but the TCK might be used for Hibernate and also we would need to have a test that validates `javax` package like `EntityJakartaAnnotationMapperSpec`, you would need to change this test to test for javax.

**Comment by alejandropg** [comment]
Ok, so maybe I will try to migrate more code. If I do I will send you separate pull requests.

Thanks a lot for your support! and see you in another PR 😉

**Pull request merged**
