### PR TITLE
Do not exit with an error if repository has a default implementation

### PR DESCRIPTION
**Pull request by andriy-dmytruk**
This is useful if a repository wants to implement and customize another interface, e.g.:

```java
interface MyRepo extends RequiredRepo, CrudRepository<MyObject, String> {

    @Override
    default getByName(String name) {
        return getById(name);
    }

    // This is to be implemented by micronaut-data instead of the above method
    getById(String id);

}
```

### CODE REVIEW

**Comment by dstepanov** [comment]
Can you please a test?

**Comment by andriy-dmytruk** [comment]
@dstepanov Is this test Ok?

**Comment by dstepanov** [comment]
I tried your example, and the visit method is skipped because the method is not abstract. Where did you find this problem?

**Comment by andriy-dmytruk** [comment]
I cannot reproduce the problem now. Strange, maybe it was something different. 
I suppose this behavior works already, indeed. Thanks.

**Pull request closed without merging**
