### PR TITLE
MongoDB: Support `arrayFilters`

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes https://github.com/micronaut-projects/micronaut-data/issues/1973

### CODE REVIEW

**Review by radovanradic — APPROVED** [review]

**Comment by radovanradic** [comment]
Looks like MongoDb test failed

**Comment by VigneshC08** [comment]
Hi @dstepanov. 

Good Day!

How to use the arrayfilters for multiple conditions

I'm trying to use below code

arrayFilters = "[{'condition.conditionType1': '"cond1'},{''condition.conditionType2': 'cond2'}]"

micronaut is throwing below error
readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is ARRAY.

So i have changed to change the syntax and tried below one,

arrayFilters = "{'condition.conditionType1': '"cond1'},{''condition.conditionType2': 'cond2'}"

Now micronaut is detecting first condition and not detecting second condition.

**Comment by dstepanov** [comment]
Should be `arrayFilters = {"..", ".."}`

**Comment by VigneshC08** [comment]
> Should be `arrayFilters = {"..", ".."}`

Thanks @dstepanov  for the response, I have tried , But i'm getting below error

'Error parsing array filter :: caused by :: Expected a single top-level field name, found 'cond1' and 'cond2'', details={}}.

PFB my full update query for your analysis

    @MongoUpdateQuery(
            filter = "{ 'filter1': 'cond1', 'priceConditions.conditionType': 'dollar'}",
            update = "{ '$set': { 'fruits.$[condition1].priceConditions.$[condition2].priceInfoList': :priceInfoLists } }",
            arrayFilters = "{'condition1.conditionType1': 'cond1','condition2.conditionType2': 'cond2'}"
    )
    void updateFruitData(List<PriceInfoList> priceInfoLists);

**Comment by dstepanov** [comment]
I'm not an expert in Mongo, you might need to ask at some user group

**Comment by VigneshC08** [comment]
No @dstepanov ,

This is not a mongo issue, This is the below command which i directly running in mongoDB

	db.collection.updateOne(
	{ "filter1": :cond, "priceConditions.conditionType": "dollar"},
   {
     "$set": {
       "fruits.$[condition1].priceConditions.$[condition2].priceInfoList": PriceInfoLists
     }
   },
   {
     "arrayFilters": [
       {'condition1.conditionType1': 'cond1'},{'condition2.conditionType2': 'cond2'}
     ]
   }
)

This is working correctly in there, while i'm implementing the micronaut, in mongo arrayfilters is in array format, But in micronaut is expecting in "{}" format, so whether in Micronaut I need to use some other syntax or currently micronaut is not support/missed to develop the array filters for multiple conditions,

I think this need to check in micronaut end.

**Comment by dstepanov** [comment]
Did you try my suggestion?
Not ` arrayFilters = "{'condition1.conditionType1': 'cond1','condition2.conditionType2': 'cond2'}"`
But ` arrayFilters = {"{'condition1.conditionType1': 'cond1'}", "{'condition2.conditionType2': 'cond2'}"}

**Comment by VigneshC08** [comment]
Thank you so much @dstepanov ,

I have tried in the format which you suggested, It's working.

**Pull request merged**
