### PR TITLE
Allow to change `@Repository`'s data source at the injection point

### LINKED ISSUE #368: Allow to inject JPA repositories for different datasources
I have an application that needs to use the same JPA repository on different datasources. At first I tried to inject it with `@PersistenceContext(name = "<datasource>")` like it works for a transaction manager but without success. I just found out that the `@Repository` annotation can be used with a datasource name. But in my opinion that is the wrong place for this declaration. It requires to define multiple repository interfaces which have exactly the same structure. Possibly that could be solved with inheritance (haven't tried) but it still contradicts the logical structure as that would be a declaration just for runtime purposes. It also makes it difficult to define repositories in libraries.

Wouldn't it be possible to use the `@PersistenceContext` annotation for repository injection too? 

### Expected Behaviour

Inject JPA repository variables for different (non-default) datasources.

### Actual Behaviour

The datasource can only be controlled by `@Repository` annotation, requiring to define multiple identical repository interfaces.

### Environment Information

- **Micronaut Version:** 1.3.0.M2
- **micronaut-data Version:** 1.0.0.M5

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes #368

### CODE REVIEW

**Comment by dstepanov** [comment]
This changes the scope of repositories from singleton to prototype

**Comment by graemerocher** [comment]
I am not sure about changing the `@Repository` annotation to also be used as a qualifier. Can we not use `@Named` here?

**Comment by dstepanov** [comment]
Well the repository annotation is not a qualified that makes this work otherwise we would need a way to make the proxy implementation defined as @Any

**Comment by dstepanov** [comment]
In other words, this approach works because `@Repository` is not a `@Qualifier` so the bean context ignores it.
If we want to support `@Named` we would need to have the introduction somehow marked as `@Any`, not sure if it's possible without changes in the core.

**Comment by graemerocher** [comment]
Ok I was just thinking about if it would conflict with `@Factory` but I guess we don't allow factory beans to produce introduction advice so maybe it is fine

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
