### PR TITLE
Don't pull in Micronaut HTTP

### LINKED ISSUE #1691: Remove dependency on Micronaut HTTP
### Expected Behavior

Micronaut Data shouldn't pull in Micronaut HTTP

### Actual Behaviour

Currently does:

```
+--- io.micronaut.data:micronaut-data-jdbc -> 3.7.2
|    +--- io.micronaut:micronaut-http:3.5.0 -> 3.6.0
|    |    +--- io.projectreactor:reactor-core:3.4.21
|    |    |    \--- org.reactivestreams:reactive-streams:1.0.4
|    |    +--- org.slf4j:slf4j-api:1.7.36
|    |    +--- io.micronaut:micronaut-inject:3.6.0 (*)
|    |    \--- io.micronaut:micronaut-core-reactive:3.6.0
|    |         +--- org.slf4j:slf4j-api:1.7.36
|    |         +--- io.micronaut:micronaut-core:3.6.0 (*)
|    |         \--- org.reactivestreams:reactive-streams:1.0.4
```

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

3.7.2

### PR DESCRIPTION
**Pull request by Goldmensch**
closes #1691

### CODE REVIEW

**Comment by dstepanov** [comment]
This task is about replacing `MediaTypeCodec` with `io.micronaut.json.JsonMapper`

**Comment by Goldmensch** [comment]
Do you mean `io.microanut.serde.JsonMapper`? Because `json-core`, in which `io.micronaut.json.JsonMapper` is defined, also pulls in Micronaut http. https://github.com/micronaut-projects/micronaut-core/blob/3.7.x/json-core/build.gradle#L9

**Comment by dstepanov** [comment]
Yes, sorry the one from Micronaut Serialization

**Comment by Goldmensch** [comment]
> Yes, sorry the one from Micronaut Serialization

Well, I took a deeper look and noticed that Micronaut Serialization uses the `JsonMapper` from `json-core. Also `serde-api` as well `serde-support` pulls in Micronaut http. I can't find a way to remove Micronaut http without a big refactor / introducing new modules.

**Pull request closed without merging**
