### PR TITLE
fixes #2008 to make a method that returns a flow to be a FIND_ALL

### LINKED ISSUE #2008: Repository methods that accept specifications and return a List of DTO always return a collection with 1 element
### Expected Behavior

Specifications that return multiple results should return a collection with all those results, or if a Flow is used, a Flow that returns multiple results.

### Actual Behaviour

Returns a list of size 1. This seems to be because the FindAllSpecificationMethodMatcher only checking if the return type is a Iterable of an Entity, instead of handling DTOs, so it falls back to FindOneSpecificationMethodMatcher.

This seems to have been "working" before by adding suspend to the method, but since [this PR was merged](https://github.com/micronaut-projects/micronaut-data/pull/1961/files#diff-ef80846aa03dfa50f9b661c79d470ead02afc62ce7112adc38b13de86e3e6f9a), it now no longer processes DTOs correctly.

### Steps To Reproduce

1. Create a Repository that uses CoroutineJpaSpecificationExecutor (or any JpaSpecificationRepository), and uses R2dbc Postgres.
2. Create a method that returns a DTO
3. Run a query that will return multiple results
4. See the result is a list of only one

Will try to create an application that reproduces.

### Environment Information

_No response_

### Example Application

https://github.com/edeesis/dto-repository

### Version

Micronaut Data 3.9.6

### PR DESCRIPTION
**Pull request by edeesis**
fixes #2008

### CODE REVIEW

**Comment by dstepanov** [comment]
Thanks! Finally managed to merge it

**Comment by edeesis** [comment]
@dstepanov any chance of this being backported to the 3.9.x line?

**Comment by dstepanov** [comment]
Maybe if you cherry my changes we can include it in 3.10

**Comment by edeesis** [comment]
@dstepanov Thanks! I dropped it into the following PR: https://github.com/micronaut-projects/micronaut-data/pull/2129

**Pull request merged**
