### PR TITLE
Optimistic locking JDBC

### PR DESCRIPTION
**Pull request by dstepanov**
This PR implements optimistic locking for JDBC by defining a `@Version` field which is included in the insert and in the update's or delete's query where statement and in a case of 0 modified rows throws `OptimisticLockException`.

PR introduces `AutoPopulatedValueProvider` to extract populating logic, I'm open to succession how to improve it. The current implementation is limited by the fact that `@DateCreated` and `@DateUpdated` needs to have the same value.

The implementation allows to use `@Version` in the update/delete statement to implement optimistic locking, it's not supported by JPA Hibernate implementation, which would require integration with auto-populated fields and for Micronaut to validate the result.

### CODE REVIEW

**Comment by graemerocher** [comment]
Interesting work, will review soon. I think in general we need to address a generic entity event API prior to this as it may influence the design of optimistic locking

**Comment by dstepanov** [comment]
Thanks, I think the basics should be the same I guess.
This was one of the things that are missing for me to migrate some of JPA projects.

BTW Looks like somehow parameters' names are lost with inheritance on Java 8 that caused tests to fail.

**Comment by dstepanov** [comment]
@graemerocher Build is passing now, only fails on the report. It would be nice if you can review the changes.

I like the idea of the entity event API but there is also a case of a simple entity update without an actual entity instance being present: `updateByIdAndVersion(@Id Long id, @Version Long version, String name)` - query should get auto-populated columns updated without an entity in the API.

**Comment by graemerocher** [comment]
@dstepanov in that case there would be a query event listener API that you should also somehow hook into

**Comment by dstepanov** [comment]
@graemerocher Are you planning to create entity event listener API? I can remove the custom auto-populate interface and keep the code as it was plus add the version handling.

**Comment by graemerocher** [comment]
@dstepanov It is on my todo list, but I have some core stuff I need to do first. If you get to it before hand let me know.

**Comment by dstepanov** [comment]
I will try to come up with something.

**Pull request closed without merging**
