### PR TITLE
rename root project name to -parent

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by graemerocher** [comment]
Doesn't doing this require the BOM to be configured correctly as well? Otherwise it will become `micronaut.data.parent.version`

**Review by melix — APPROVED** [review]

**Comment by melix** [comment]
Note that a side effect of changing the root project name is that history for build scans will be lost for that project.

**Comment by graemerocher** [comment]
And what about the BOM?

**Comment by melix** [comment]
No, with the latest build plugins, we handle "-parent" in the name automatically.

**Comment by melix** [comment]
so this should probably be upgraded too: https://github.com/micronaut-projects/micronaut-data/blob/master/gradle.properties#L4

**Pull request merged**
