### PR TITLE
Add synchronous Kotlin Data Repository Interfaces

### PR DESCRIPTION
**Pull request by charlie-harvey**
The `CoroutineCrudRepository` and the `CoroutinePageableCrudRepository` interfaces are great if you want to run Reactive/Asynchronous database calls, I feel there is a need for Synchronous database interaction. I have been using these interfaces in my own code for a while now and really like them. Figured I could create this PR and add `KotlinCrudRepository` which adds the `@Blocking` annotation and removes the `suspend` keyword from each of the functions.

These interfaces mean I can use things like `?` instead of `Optional`. And I can leave off all the `@Nullable` and `@NotNull` annotations. This makes all my sub interfaces "pure Kotlin" which is super nice to have.

I went into each of the example kotlin modules and changed all of the tests to use the new Repositories.

### CODE REVIEW

**Comment by dstepanov** [comment]
Can you please copy the repositories and the tests in a way we test both interfaces?

**Comment by dstepanov** [comment]
BTW it looks like your commit doesn’t match the github username

**Comment by charlie-harvey** [comment]
Not sure what happened with the username. I will probably drop this PR and start again.

Makes sense about copying the tests. Will do that. Thanks.

**Comment by dstepanov** [comment]
No worries, you can just use force push to override the commits

**Comment by graemerocher** [comment]
I am not sure I understand why kotlin interfaces are needed? Can you elaborate how `KotlinCrudRepository` is different from the Java version?

**Comment by graemerocher** [comment]
sorry missed the point about nullability, I think a new module makes sense here, `micronaut-data-kotlin` or something

**Comment by charlie-harvey** [comment]
I can work that out. I have some questions before I begin:

1) What do you think of the name `KotlinCrudRepository`? Can you think of anything better? Is it good fine?

2) As for the tests to copy, which ones and in which fashion? Copy an entire `-doc` module or just add more tests/examples to the existing module?

Thanks!

**Comment by dstepanov** [comment]
@charlie-harvey Sorry for the late reply.
1. Looks fine to me. Maybe it would be better to introduce `micronaut-data-kotlin` module with Kotlin repositories and utils.
2. It would be enough to add them to the existing `doc` to test them or test them in the new module

**Pull request closed without merging**
