### PR TITLE
Set useStandardizedProjectNames to true, update project and tests dependencies

### PR DESCRIPTION
**Pull request by radovanradic**
Updated flag useStandardizedProjectNames to true and also did some modules and tests cleanup dependencies, mainly to refer project module instead of gradle dependencies.

### CODE REVIEW

**Comment by radovanradic** [comment]
One thing that we had issue in latest serde dependency is referring "io.micronaut.data:micronaut-data-mongodb" was looking up gradle vs project itself so fixing compile error in project did not have effect. Want to avoid that issue.

As for changing `useStandardizedProjectNames` I have noticed that is used in micronaut-sql, not sure which is preferred but I thought wouldn't hurt changing in this effort.

**Comment by dstepanov** [comment]
Maybe we can delete those extra depends on if the project doesn't run in parallel anymore

**Comment by radovanradic** [comment]
Btw, you mean this:
```
if (micronautBuild.environment.githubAction.get()) {
        // Let some of the checks tests first so the test containers don't eat all the memory
        mustRunAfter ":micronaut-data-jdbc:test"
    }
```
or this 
```
tasks.register("testExamples") {
    dependsOn "test"
}
```
or both?

**Comment by dstepanov** [comment]
The first one, the second one I still use sometimes to run the example tests only

**Comment by radovanradic** [comment]
> The first one, the second one I still use sometimes to run the example tests only

Changed

**Pull request merged**
