### PR TITLE
Added Spring Data JDBC to the benchmarks

### PR DESCRIPTION
**Pull request by odrotbohm**
I've added Spring Data JDBC to the benchmarks for comparison. Only difference in the actual benchmark is that it requires the query to be defined manually right now.

Oh, and watch the numbers for the JPA one, too. It's been upgraded to Boot 2.2 M5.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the PR! Will check it out

**Comment by odrotbohm** [comment]
Thanks, Graeme. Is there a way to run all the benchmarks at once? It's a bit cumbersome to bootstrap them all individually.

**Comment by graemerocher** [comment]
yeah I haven't worked that out yet.. maybe a custom gradle task in the root could do it

**Comment by graemerocher** [comment]
@odrotbohm Nice improvements on the JPA side! Both JPA ones give me roughly the same numbers now (92k ops/sec). Although I don't have the same test hard ware, just an old MacBook Pro 2013 :)

**Comment by graemerocher** [comment]
@odrotbohm Do you know what this error means for the spring-data JPA benchmark?:

https://travis-ci.org/micronaut-projects/micronaut-data/jobs/569773979#L1308

Seems to only occur on JDK 11

**Comment by odrotbohm** [comment]
Never seen this before. Is there a more verbose stacktrace somewhere? I can run the benchmark just fine on JDK 11 locally.

**Comment by graemerocher** [comment]
Seems to only fail when running `bootJar` with this stack trace:

```
* What went wrong:
org.springframework.asm.Type.getMethodType(Lorg/springframework/asm/Type;[Lorg/springframework/asm/Type;)Lorg/springframework/asm/Type;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: org.springframework.asm.Type.getMethodType(Lorg/springframework/asm/Type;[Lorg/springframework/asm/Type;)Lorg/springframework/asm/Type;
        at org.springframework.boot.loader.tools.MainClassFinder.<clinit>(MainClassFinder.java:61)
        at org.springframework.boot.gradle.plugin.MainClassConvention.findMainClass(MainClassConvention.java:73)
        at org.springframework.boot.gradle.plugin.MainClassConvention.resolveMainClass(MainClassConvention.java:67)
        at org.springframework.boot.gradle.plugin.MainClassConvention.call(MainClassConvention.java:62)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
```

I have disabled that for the moment as a workaround https://github.com/micronaut-projects/micronaut-data/commit/a935dc6a6b9516c99c962295b9b693ccf757448e

**Comment by odrotbohm** [comment]
We're looking into the issue with the `bootJar` task. That said, I actually forgot to switch the JDBC project to Boot 2.2 M5. Do you want me to create another PR or would you mind just amending the changes necessary?

**Comment by odrotbohm** [comment]
We have a temporary workaround to make the `bootJar` tasks work. I'll create a new PR and include the upgrade to Boot 2.2 M5 for the JDBC module as well. Beware, better benchmark numbers 😬.

**Comment by graemerocher** [comment]
Thanks!

**Comment by graemerocher** [comment]
yeah it is fine I will merge both PRs

**Comment by graemerocher** [comment]
@odrotbohm Thanks for reporting this. Thanks to this report we discovered some inefficiencies in the Micronaut implementation and have addressed those in the master branch. Now the numbers for me look like the following on a relatively old MacBook Pro 2013:

* Spring Data JPA: 92k ops/sec
* Micronaut Data JPA: 97k ops/sec
* Spring Data JDBC: 250k ops/sec
* Micronaut Data JDBC: 300k ops/sec

The difference between the JPA implementations is not that big and since we are now (at compilation time) building the same indexes as Spring Data I imagine the difference is mainly down to the lack of reflection, but maybe there is something else you can find in Spring Data JPA.

The difference between the JDBC implementations and the reason my Micronaut's implementation was slower before is that we discovered a performance bug in that for constructor arguments  Micronaut Data was also calling setters for properties that are also constructor arguments after constructing the object resulting in 2 extra calls to read the column from the database, whilst Spring Data JDBC was not doing this. After we switched that and optimized a few other things things are looking better again.

As for the original article I will have access to the hardware which we used to run the benchmarks on Thursday morning and will update the article with the latest data following improvements in both Spring Data and Micronaut Data. Thanks again for the PR and report!

**Comment by graemerocher** [comment]
> Thanks, Graeme. Is there a way to run all the benchmarks at once? It's a bit cumbersome to bootstrap them all individually.

You can now run all the benchmarks with `./gradlew benchmarks`

**Comment by odrotbohm** [comment]
Nice! I almost expected that there was still room for improvement :). The Micronaut Data JPA benchmarks currently don't produce any numbers for me as I run into the following exception:

```
org.hibernate.QueryException: Named parameter not bound : p1
        at org.hibernate.query.internal.QueryParameterBindingsImpl.verifyParametersBound(QueryParameterBindingsImpl.java:210)
        at org.hibernate.query.internal.AbstractProducedQuery.beforeQuery(AbstractProducedQuery.java:1423)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1523)
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1567)
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueResultOptional(AbstractProducedQuery.java:1518)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findOne$2(HibernateJpaOperations.java:159)
        at io.micronaut.data.hibernate.runtime.spring.SpringHibernateTransactionOperations.lambda$executeRead$1(SpringHibernateTransactionOperations.java:59)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at io.micronaut.data.hibernate.runtime.spring.SpringHibernateTransactionOperations.executeRead(SpringHibernateTransactionOperations.java:58)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findOne(HibernateJpaOperations.java:124)
        at io.micronaut.data.runtime.intercept.DefaultFindOneInterceptor.intercept(DefaultFindOneInterceptor.java:47)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:78)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:218)
        at example.BookRepository$Intercepted.findByTitle(Unknown Source)
        at benchmarks.SimpleQuery.measureFinder(SimpleQuery.java:43)
        at benchmarks.generated.SimpleQuery_measureFinder_jmhTest.measureFinder_thrpt_jmhStub(SimpleQuery_measureFinder_jmhTest.java:143)
        at benchmarks.generated.SimpleQuery_measureFinder_jmhTest.measureFinder_Throughput(SimpleQuery_measureFinder_jmhTest.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

The JDBC ones fail with this one:

```
Parameter "#1" is not set; SQL statement:
SELECT book_.id,book_.title,book_.pages FROM book book_ WHERE (book_.title = ?) [90012-199]
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:193)
        at io.micronaut.data.jdbc.runtime.spring.SpringJdbcTransactionOperations.lambda$executeRead$1(SpringJdbcTransactionOperations.java:63)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at io.micronaut.data.jdbc.runtime.spring.SpringJdbcTransactionOperations.executeRead(SpringJdbcTransactionOperations.java:60)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:151)
        at io.micronaut.data.runtime.intercept.DefaultFindOneInterceptor.intercept(DefaultFindOneInterceptor.java:47)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:78)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:218)
        at example.BookRepository$Intercepted.findByTitle(Unknown Source)
        at benchmarks.SimpleQuery.measureFinder(SimpleQuery.java:43)
        at benchmarks.generated.SimpleQuery_measureFinder_jmhTest.measureFinder_thrpt_jmhStub(SimpleQuery_measureFinder_jmhTest.java:143)
        at benchmarks.generated.SimpleQuery_measureFinder_jmhTest.measureFinder_Throughput(SimpleQuery_measureFinder_jmhTest.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

We have a bit of headroom in JDBC which we decided not to pursue for this release train as we're already in the RC phase. But it's definitely going to come after the GA release. I am suspecting we're going to move into ballparks similar to the JPA differences.

What everyone should remember about these numbers is that they're clean room benchmarks that avoid any other kind of overhead whatsoever. If you take those operations even into an only slightly more real world context by e.g. speaking to a locally running database, the ops/sec collapse into the four digit area and even a difference in performance of more than 100% (comparing Spring Data JPA and Spring Data JDBC) practically becomes invisible. I think everyone can make up their minds what that means for a 5% performance advantage in the clean room environment.

Zooming out of the detailed numbers a bit, I still think there's tremendous value in the competing approaches as they create incentives for all involved parties to move forward and focus. What I still think is a bit odd is the exaggeration of the effect of JDK proxies and reflection  on runtime performance. Given the numbers today there's a 5% difference for the JPA side of things under benchmark conditions and suggesting this is any kind of "groundbreaking" or "revolutionary" feels a bit over the top. I know, marketing, significance, etc. but maybe we can put more emphasis on exchanges like these here as they seem to be more well-grounded and productive.

**Comment by graemerocher** [comment]
1. The error is probably because you need to perform a clean recompile. We altered the precomputed query indexes so there is a new format that requires a recompile.

2. Absolutely you will undoubtedly get the runtime performance to be within the 5% range which is probably the difference between JDK proxy and reflection free access, it is just a matter of computing at runtime the correct data structures. After that Micronaut and Spring run on the same VM after all.

3. Yes in a production scenario for sure the 5% will be less significant, nevertheless runtime performance was just one of the numerous benefits we outlined in the original article. You seem quite focused on the runtime performance one for whatever reason.

4. Every new product announcement has its fair share of marketing and that is standard for every single corporate blog or every tech organization world wide (not sure why Micronaut and Object Computing need to be any different?). It has also become customary for members of the Spring team to dismiss Micronaut as not particularly innovative. It serves your own marketing strategy well. 

In addition, runtime performance is just one reason why we believe Micronaut and Micronaut Data are innovative. Memory consumption, startup time, time to first request (for serverless) are all additional metrics that we are focused on optimizing from a performance perspective. In addition developer experience with compile time checking and GraalVM native support without requiring any additional GraalVM metadata. All of these aspects went into the design of Micronaut and Micronaut Data. 

I personally prefer to let users be the judge, evaluating both and choose whichever framework suites there needs. Hopefully many users choose Micronaut and Micronaut Data, it means we are doing something right.

**Comment by odrotbohm** [comment]
> You seem quite focused on the runtime performance one for whatever reason.

There are two aspects playing into this: the general impression being created that the Spring team does not focus on performance (all memory, startup, runtime, see the recent Twitter thread for proof of people thinking this) and it needing external incentives to do so. That's just wrong. Literally every RC phase of every Spring Data release train has seen this kind of performance review as you can investigate in the commit logs.

The second aspect is a transitive interest: no matter how nuanced you describe things in the article, what people remember is a table with numbers derived from some benchmark showing up at my desk "We're now using Micronaut because JPA is twice as fast on it." And that forces me again and again to spend time on correcting these impressions. Time I could've much rather spent on interactions like this one that really bring both projects forward.

> not sure why Micronaut and Object Computing need to be any different?

Because new tech – more than established – has to build up relevance and exaggerating benefits of it helps with that. If some new stack gives me 50% more real-world performance, I'd be inclined to give it a try. If it's a mere 5%, it might just not be worth the hassle. I.e. I can understand that there are incentives to make the numbers look like what you get is the former. I am happy to be wrong about this, but not clearly contextualizing the numbers ("The difference looks like this on a real database.") leaves me with the impression that the lack of that is on purpose.

> It has also become customary for members of the Spring team to dismiss Micronaut as not particularly innovative.

I'd love to see prove of that in particular as I can assure you that nobody here thinks Micronaut is not innovative. It's approach is definitely different and depending on how you look at Quarkus might even be unprecedented at the time of announcement (no judgement on that story from my side). All kudos for that to the team! Nobody would ever dispute that. What I indeed see sceptical is the the actual effect of this approach in real-world projects.

Cheers! 🙃

**Comment by graemerocher** [comment]
Just an update I had hoped to update the article but didn’t get time before leaving for vacation. I will be back at the end of the month and will update them. Thanks for the feedback

**Comment by graemerocher** [comment]
Returning to this after vacation. I have updated to the blog post with the latest numbers.

Regarding the comments 

> the general impression being created that the Spring team does not focus on performance

No one from the Micronaut team nor Object Computing has ever said this. In fact we have pointed out the performance optimizations in Boot and how they will benefit Grails users (which will continue to be based on Boot). We cannot control third parties who form their own opinions.

> no matter how nuanced you describe things in the article, what people remember is a table with numbers derived from some benchmark showing up at my desk 

The numbers were correct at the time of writing, my apologies if I have created work for you, that was not the Micronaut's teams intention.

**Comment by odrotbohm** [comment]
> Returning to this after vacation. I have updated to the blog post with the latest numbers.

Thanks for that.

> > no matter how nuanced you describe things in the article, what people remember is a table with numbers derived from some benchmark showing up at my desk
> 
> The numbers were correct at the time of writing, my apologies if I have created work for you, that was not the Micronaut's teams intention.

I think you misunderstood. Neither did I dispute that the numbers were correct at the time, nor do I mind working on stuff like this. :) What I found problematic is that they weren't properly contextualized as people seem to think that what was presented was the real world performance difference and now the burden is on me/us to make all this contextualization, explaining that these are benchmark numbers and those differences do not reflect into real world code to the perceived extend etc.

**Comment by graemerocher** [comment]
In the spirit of open collaboration and just FYI we have committed our own fork of Spring transaction management which ports it to Micronaut AOP, modernizes it, eliminates waste, removes all uses of reflection and runtime proxies, reduces our JAR size by 4MB, our Graal native image size by 20MB and eliminates the only dependency on Spring that existed.

Net result is the JDBC benchmark for Micronaut Data is up to 430k ops/sec from 330k ops/sec. I have updated the blog post to reflect that. So when you get round to optimizing JDBC you may want to look at the transaction management part in Spring which has quite a few inefficiencies.

I have yet to port the Hibernate transaction management to Micronaut AOP, once I have done that I will update the JPA benchmark with the results.

**Pull request merged**
