### PR TITLE
define Platform version in libs.versions.toml

### PR DESCRIPTION
**Pull request by sdelamo**
This PR updates gradle plugin and test resource versions. 

Moreover, it defines platform version in a single place.

### CODE REVIEW

**Comment by sdelamo** [comment]
Gradle Scan https://ge.micronaut.io/s/vnzdvnweypou6

**Comment by sdelamo** [comment]
@msupic why are you removing flyway?

**Comment by msupic** [comment]
@sdelamo - because `schema-generate` is used in `application.yml`. We should not use `flyway` and `schema-generate` together since `flyway` fails because the schema has been already generated.
`io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.`

**Comment by msupic** [comment]
@sdelamo - also docs referencing this for `schema-generate` example so I removed flyway

**Comment by msupic** [comment]
The mariadb tests are failing with the following error
`io.r2dbc.spi.R2dbcTransientResourceException: No decoder for type java.util.UUID and column type VARSTRING`. Those tests are using `mariadb` test container. The same tests in the `master` branch are using `mysql` test container and those are not failing.

PR:
`16:09:23.351 [main] DEBUG i.m.t.c.TestResourcesClientPropertyExpressionResolver - Resolved expression 'r2dbc.datasources.default.url' to 'r2dbc:mariadb://localhost:49178/test'`

Master:
`16:11:42.941 [main] DEBUG i.m.t.c.TestResourcesClientPropertyExpressionResolver - Resolved expression 'r2dbc.datasources.default.url' to 'r2dbc:mysql://localhost:49179/test'`

**Comment by msupic** [comment]
@sdelamo @graemerocher @dstepanov - I fixed issues that were caused by replacement of `mysql` with `mariadb` container. Please take a look and let me know if something needs to be changed.

**Pull request merged**
