### PR TITLE
Replace javax.annotation to jakarta.annotation.

### PR DESCRIPTION
**Pull request by altro3**
Fix checkstyle errors.
Fix doclint errors and warnings.

### CODE REVIEW

**Comment by altro3** [comment]
Some problems with CI-CD:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
RequestError [HttpError]: Resource not accessible by integration
Error: Unhandled error: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4561:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/micronaut-projects/micronaut-data/issues/2058/comments',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 04 Mar 2023 12:28:55 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': '53C0:60B2:1220119:258E9D8:64033986',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '999',
      'x-ratelimit-reset': '1677936535',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/micronaut-projects/micronaut-data/issues/2058/comments',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.5.1 Node.js/12.22.7 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"❌ Java CI 17 failed: "}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
```

**Comment by dstepanov** [comment]
It would be better to make those changes in the master for the next major version.

**Comment by altro3** [comment]
@dstepanov But javax annotation was replaced by jakarta annotation in micronaut 3.0.0. As I understand, this is bug  :-)

**Comment by dstepanov** [comment]
Not really, Micronaut still supports `javax` in Micronaut 3

**Comment by altro3** [comment]
@dstepanov In my opinion, this is still a bug. I understand. that micronaut supports both libraries, but the transition from javax to jakarta was in the 3rd version. As I understand it, this means that all projects of the micronaut family had to switch to using jakarta.annotation , but there was support for those who use micronaut. In addition, it seems strange to me to use 2 libraries inside one project - mikrnavt data. That is, both javax and jakarta are now used there. IMHO it is better to use one thing, but there is clearly no point in rolling back to javax, which is why I corrected the remaining places on jakarta.

Also, because of these places, I can't drop the javax.annotation dependency in my project, but after these changes, I can.

In general, it would still be good to see this in version 3.9 without waiting for version 4

**Pull request closed without merging**
