### PR TITLE
Add JOOQ example for testing

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by dstepanov** [comment]
@msupic Any idea why Hibernate started to fail in the native?

**Comment by dstepanov** [comment]
@msupic @melix This is very strange. Somehow `./gradlew doc-examples:hibernate-example-java:nativeTest` is passing in the master but fails on this branch. I can even reproduce it locally. Any idea?

**Comment by dstepanov** [comment]
The test passes if I remove the new project from the `setting.gradle`

**Comment by dstepanov** [comment]
Thanks @radovanradic Not sure why was this happening

**Comment by radovanradic** [comment]
Maybe jooq from micronaut-sql somehow brought older graalvm repository version. I remember that logging dialect issue was resolved with 0.3.2 version so setting this explicit version resolved the issue in micronaut-data (also for PR https://github.com/micronaut-projects/micronaut-data/pull/2290)

**Pull request merged**
