### PR TITLE
 Remove `setMaxResults` for JPA. Fixes #863 

### LINKED ISSUE #863: Unnecessary setMaxResults(1) degrades query performance
### Task List

- [x] Steps to reproduce provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

When querying a single entity that has a lazy `@ManyToMany` relation and eager fetching it through the `@Repository`, Hibernate will log a warning because it had to choose a low performance in-memory query strategy.

### Steps to Reproduce

Let's begin with an entity called Profile. A profile can have N menus on it, so we declare those entities like this:

```java
@Entity
public class Profile {

    @Id
    @GeneratedValue
    private Integer id;

    private String name;

    @ManyToMany
    @JoinTable(name = "profile_menu",
            joinColumns = @JoinColumn(name = "profile_id"),
            inverseJoinColumns = @JoinColumn(name = "menu_id"))
    private List<Menu> menus;
}

@Entity
public class Menu {

    @Id
    private Integer id;

    private String route;
}
```

Then we create a repository and a custom query to eager fetch those menus when querying a profile:

```java
@Repository
public interface ProfileRepository extends JpaRepository<Profile, Integer> {

    @Query("select p from Profile p left join fetch p.menus where p.id = :id")
    Optional<Profile> findById(Integer id);
}
```

When executing the `findById` we will receive a profile with all its menus, avoiding the lazy exception. But something bad happend and this is shown in the log:

```
WARN  o.h.h.i.ast.QueryTranslatorImpl : HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!
```

Look for this warning on google and you can find some users reporting this issue (not related to micronaut, but hibernate or spring/hibernate), and those issues usually is about the user trying to paginate and eager fetch at the same time. I didn't find a issue about querying a single result and this warning popping up.

After some investigation I have found that the HibernateJpaOperations is setting the max results to 1 in [this line](https://github.com/micronaut-projects/micronaut-data/blob/1660e2e723d13f0b5a58c77eb2c8248629543bb3/data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java#L174). This `setMaxResults` will call `RowSelection.setMaxRows(int maxRows)`, which will latter result in Hibernate raising that warning.

To test if this `q.setMaxResults(1)` is really necessary, I set a breakpoint after the `setMaxRows(int maxRows)` and changed it to `null`. After resuming the application, Hibernate queried the profile and eager fetched the menus just fine, without any warning and in-memory crazy stuff.

Is there a specific reason for this `q.setMaxResults(1)` in the `findOne` implementation? Wouldn't this shadow a developer error when the developer think it is querying a single result, but the SQL is wrong and querying N results, but micronaut shadows it by limiting it back to 1? If the result is 2+ rows, wouldn't be better to throw an exception? (I think spring does that).

### Expected Behaviour

To eager fetch lazy associations using the repository definition without having hibernate to choose a bad performance query strategy.

### Actual Behaviour

Micronaut forces the `findOne` to actually find just one, which confuses Hibernate when eager fetching lazy associations.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.1
- **JDK Version:** 11

### PR DESCRIPTION
**Pull request by dstepanov**
This might be a breaking change that we would want to postpone to the major release.
Also, we might need to introduce the same error for JDBC repositories.

### CODE REVIEW

**Comment by graemerocher** [comment]
yeah I think this might break some apps, is using `q.uniqueResultOptional` not possible?

**Comment by dstepanov** [comment]
That's the same method but with `Optional` result. I can use` list()` method and get the first item for now, but I think in the next major version we should throw an error if multiple values returned.

**Comment by graemerocher** [comment]
I think it would be more efficient and probably not breaking to call `query.iterate()` and use `hasNext()` to check if there is a result or not. This would fix the issue for the current version without introducing a breaking change around unique result exception

**Comment by dstepanov** [comment]
I’m going to try to use the iterator

**Comment by dstepanov** [comment]
`query.iterate()` doesn't work in some cases, I reverted to using `list`.

**Pull request merged**
