### PR TITLE
Create time columns with right type

### LINKED ISSUE #1598: It creates column with type Date, but should be Time
### Expected Behavior

Create column with type Time

	@MappedProperty (value = "wakeup_time")
	private Time wakeUpTime;

### Actual Behaviour

```txt
mysql> desc person;
+----------------+--------------+------+-----+----------------------+-------------------+
| Field          | Type         | Null | Key | Default              | Extra             |
+----------------+--------------+------+-----+----------------------+-------------------+
| id             | int          | NO   |     | NULL                 |                   |
| wakeup_time    | date         | NO   |     | NULL                 |                   |
+----------------+--------------+------+-----+----------------------+-------------------+
```

### Steps To Reproduce

application.yml

```yml
micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: aaa
    password: '123'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
```

### Environment Information

_No response_

### Example Application

_No response_

### Version

3.5.2

### PR DESCRIPTION
**Pull request by Goldmensch**
closes #1598

### CODE REVIEW

**Comment by Goldmensch** [comment]
The pr still has issues with OracleDB, so a review is not required yet.

**Comment by Goldmensch** [comment]
@dstepanov Do you have an idea how to fix the java 17 ci?

**Comment by dstepanov** [comment]
I will try to rerun it.

**Comment by Goldmensch** [comment]
@dstepanov could you run the ci with debug mode on?

**Comment by dstepanov** [comment]
Can you please annotate `r2dbc-example-groovy/build/classes/groovy/test/example/BookControllerTest``spock.lang.Retry`?

**Comment by dstepanov** [comment]
Thanks @Goldmensch!

**Pull request merged**
