### PR TITLE
[data] Update common files for branch 4.9.x

### PR DESCRIPTION
**Pull request by micronaut-build**
Update common files

### CODE REVIEW

**Comment by dstepanov** [comment]
@radovanradic Can you please move it to `custom-suppressions.xml` like in Core https://github.com/micronaut-projects/micronaut-core/blob/4.5.x/config/checkstyle/custom-suppressions.xml

**Comment by radovanradic** [comment]
> @radovanradic Can you please move it to `custom-suppressions.xml` like in Core https://github.com/micronaut-projects/micronaut-core/blob/4.5.x/config/checkstyle/custom-suppressions.xml

Done

**Comment by dstepanov** [comment]
Looks like it got overriden :(

**Comment by radovanradic** [comment]
The PR was recreated and removed added file. I added it again and when the build is complete this can be merged so file should be kept then.

**Review by radovanradic — APPROVED** [review]

**Pull request merged**
